#!/usr/bin/env bash

function get_current_script_dir()
{
    local script_source="${BASH_SOURCE[0]}"
    while [ -h "$script_source" ]; do
        local script_dir="$( cd -P "$( dirname "$script_source" )" && pwd )"
        script_source="$(readlink "$script_source")"
        [[ $script_source != /* ]] && script_source="$script_dir/$script_source"
    done
    script_dir="$( cd -P "$( dirname "$script_source" )" && pwd )"
    echo "${script_dir}"
}

export PATH=${PATH}:$(get_current_script_dir)

